# Small libretro core and optional static library for private FMS verification.
set(LIBMGBA_ONLY ON CACHE BOOL "" FORCE)
set(BUILD_STATIC ON CACHE BOOL "" FORCE)
set(BUILD_SHARED OFF CACHE BOOL "" FORCE)
set(BUILD_LIBRETRO ON CACHE BOOL "" FORCE)
foreach(option BUILD_QT BUILD_SDL BUILD_GL BUILD_GLES2 BUILD_GLES3
        USE_LUA USE_FFMPEG USE_PNG USE_ZLIB USE_LZMA USE_SQLITE3 USE_LIBZIP
        USE_MINIZIP USE_JSON_C USE_FREETYPE USE_ELF)
  set(${option} OFF CACHE BOOL "" FORCE)
endforeach()
